#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "sql.y".
#

require 'racc/parser.rb'

#
class SqlParser < Racc::Parser

module_eval(<<'...end sql.y/module_eval...', 'sql.y', 59)

load '../lib/kaigyo/tokenizer.rb'
def parse(str)
  tokenizer = ::Kaigyo::Tokenizer.new(str)
  @q = tokenizer.token_analysis

  pp @q
  
  do_parse end

def next_token
  @q.shift
end

...end sql.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    14,    50,    51,    27,     4,    24,    14,    25,    26,     5,
    27,    14,    24,    21,    25,    26,    15,    16,    17,    14,
    18,    19,    15,    16,    17,    14,    18,    15,    16,    17,
    28,    18,    19,    14,    27,    15,    16,    17,    27,    18,
    27,    15,    16,    17,    27,    18,    24,    43,    25,    26,
    27,    45,    24,    27,    25,    26,     4,    65,    66,    53,
    54,    55,    56,    57,    47,    48,    58,    59,    61,    62,
    27,    27,    27,    69,    70,    27,    72 ]

racc_action_check = [
     2,    36,    36,     4,     0,     4,     8,     4,     4,     1,
    16,     9,    16,     3,    16,    16,     2,     2,     2,    10,
     2,     2,     8,     8,     8,    11,     8,     9,     9,     9,
     5,     9,     7,    13,    14,    10,    10,    10,    15,    10,
    17,    11,    11,    11,    21,    11,    21,    18,    21,    21,
    45,    23,    45,    52,    45,    45,    24,    52,    52,    37,
    37,    37,    37,    37,    27,    35,    41,    42,    46,    47,
    48,    49,    58,    61,    63,    69,    70 ]

racc_action_pointer = [
     2,     9,    -4,    10,    -4,    30,   nil,     7,     2,     7,
    15,    21,   nil,    29,    27,    31,     3,    33,    36,   nil,
   nil,    37,   nil,    43,    54,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    60,   -12,    44,   nil,   nil,
   nil,    58,    44,   nil,   nil,    43,    58,    62,    63,    64,
   nil,   nil,    46,   nil,   nil,   nil,   nil,   nil,    65,   nil,
   nil,    67,   nil,    68,   nil,   nil,   nil,   nil,   nil,    68,
    69,   nil,   nil ]

racc_action_default = [
   -50,   -50,   -48,   -13,   -50,   -50,    -1,   -48,    -3,    -4,
    -5,    -6,   -11,   -16,   -50,   -50,   -50,   -50,   -50,   -49,
   -12,   -50,   -14,   -20,   -50,   -24,   -25,   -26,    73,    -2,
    -7,    -8,    -9,   -10,   -17,   -50,   -28,   -50,   -40,   -41,
   -42,   -43,   -45,   -47,   -15,   -50,   -50,   -50,   -50,   -50,
   -33,   -34,   -50,   -35,   -36,   -37,   -38,   -39,   -50,   -46,
   -21,   -22,   -27,   -18,   -29,   -30,   -31,   -32,   -44,   -50,
   -50,   -23,   -19 ]

racc_goto_table = [
    35,    37,    22,    42,    40,     1,    38,     6,    34,     7,
    20,    49,    29,    52,    39,    30,    31,    32,    33,    44,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    46,
   nil,   nil,   nil,   nil,    37,    37,   nil,   nil,    67,    63,
    64,   nil,   nil,    60,    42,    68,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    71 ]

racc_goto_check = [
    14,    14,    12,    14,    19,     1,    15,     3,     5,     4,
    11,    17,     3,    18,    12,     4,     4,     4,     4,    12,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     1,
   nil,   nil,   nil,   nil,    14,    14,   nil,   nil,    14,    15,
    15,   nil,   nil,    12,    14,    19,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,     5,   nil,     5,     7,    -5,   nil,   nil,   nil,   nil,
   nil,     7,    -2,   nil,   -14,    -9,   nil,   -25,   -24,   -13,
   nil ]

racc_goto_default = [
   nil,   nil,     2,   nil,   nil,     8,     9,    10,    11,    12,
     3,   nil,   nil,    13,    23,   nil,    36,   nil,   nil,   nil,
    41 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 27, :_reduce_1,
  3, 27, :_reduce_2,
  1, 30, :_reduce_3,
  1, 30, :_reduce_4,
  1, 30, :_reduce_5,
  1, 30, :_reduce_6,
  2, 30, :_reduce_7,
  2, 30, :_reduce_8,
  2, 30, :_reduce_9,
  2, 30, :_reduce_10,
  1, 30, :_reduce_11,
  2, 28, :_reduce_12,
  1, 28, :_reduce_13,
  2, 36, :_reduce_14,
  2, 37, :_reduce_15,
  1, 31, :_reduce_16,
  2, 31, :_reduce_17,
  4, 39, :_reduce_18,
  6, 39, :_reduce_19,
  1, 38, :_reduce_none,
  3, 38, :_reduce_21,
  3, 38, :_reduce_22,
  5, 38, :_reduce_23,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 40, :_reduce_none,
  3, 40, :_reduce_27,
  1, 41, :_reduce_none,
  3, 41, :_reduce_29,
  3, 42, :_reduce_30,
  3, 42, :_reduce_31,
  3, 42, :_reduce_32,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  2, 32, :_reduce_40,
  2, 33, :_reduce_41,
  2, 34, :_reduce_42,
  1, 45, :_reduce_43,
  3, 45, :_reduce_44,
  1, 46, :_reduce_45,
  2, 46, :_reduce_46,
  2, 35, :_reduce_47,
  0, 29, :_reduce_none,
  1, 29, :_reduce_49 ]

racc_reduce_n = 50

racc_shift_n = 73

racc_token_table = {
  false => 0,
  :error => 1,
  :select => 2,
  :from => 3,
  :join => 4,
  :on => 5,
  :as => 6,
  :identifier => 7,
  :punctuation => 8,
  :left_paren => 9,
  :right_paren => 10,
  :number => 11,
  :literal => 12,
  :and => 13,
  :or => 14,
  :equal => 15,
  :less_than => 16,
  :less_than_equal => 17,
  :greater_than => 18,
  :greater_than_equal => 19,
  :where => 20,
  :group_by => 21,
  :order_by => 22,
  :order_option => 23,
  :limit => 24,
  :semi_colon => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "select",
  "from",
  "join",
  "on",
  "as",
  "identifier",
  "punctuation",
  "left_paren",
  "right_paren",
  "number",
  "literal",
  "and",
  "or",
  "equal",
  "less_than",
  "less_than_equal",
  "greater_than",
  "greater_than_equal",
  "where",
  "group_by",
  "order_by",
  "order_option",
  "limit",
  "semi_colon",
  "$start",
  "sql",
  "select_and_from",
  "semi_colon_char",
  "optional_clauses",
  "join_clauses",
  "where_clause",
  "group_by_clause",
  "order_by_clause",
  "limit_clause",
  "select_clause",
  "from_clause",
  "idents",
  "join_clause",
  "ident",
  "conditions",
  "condition",
  "and_or",
  "operator",
  "order_by_idents",
  "order_by_ident" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'sql.y', 2)
  def _reduce_1(val, _values, result)
     result = val.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 3)
  def _reduce_2(val, _values, result)
     result = val.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 6)
  def _reduce_3(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 7)
  def _reduce_4(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 8)
  def _reduce_5(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 9)
  def _reduce_6(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 10)
  def _reduce_7(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 11)
  def _reduce_8(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 12)
  def _reduce_9(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 13)
  def _reduce_10(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 14)
  def _reduce_11(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 17)
  def _reduce_12(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 18)
  def _reduce_13(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 19)
  def _reduce_14(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 21)
  def _reduce_15(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 23)
  def _reduce_16(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 24)
  def _reduce_17(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 25)
  def _reduce_18(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 26)
  def _reduce_19(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'sql.y', 28)
  def _reduce_21(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 29)
  def _reduce_22(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 30)
  def _reduce_23(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'sql.y', 34)
  def _reduce_27(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'sql.y', 37)
  def _reduce_29(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 38)
  def _reduce_30(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 39)
  def _reduce_31(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 40)
  def _reduce_32(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'sql.y', 43)
  def _reduce_40(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 44)
  def _reduce_41(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 45)
  def _reduce_42(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 46)
  def _reduce_43(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 47)
  def _reduce_44(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 48)
  def _reduce_45(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 49)
  def _reduce_46(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 50)
  def _reduce_47(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 48 omitted

module_eval(<<'.,.,', 'sql.y', 52)
  def _reduce_49(val, _values, result)
     result = val
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class SqlParser


if __FILE__ == $0
TEST_SQL =<<-SQL
  select a as aa , b as bb, (select c from hoge where c.id = 1 or hoge.id = 1) as cc inner join piyo as p on p.id = a.id left outer join aaaaa as aaa on aaa.id = a.id where aaa.gid > 1 or aaa.id > 0;
SQL
  begin
    puts '> Please input SQL'
    sql = gets.chomp
    # ast = SqlParser.new.parse(TEST_SQL)
    parsed = SqlParser.new.parse(sql)
    puts "AST:"
    pp parsed
  rescue Racc::ParseError => e
    $stderr.puts e
    $stderr.puts e.backtrace
  end
end
