#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "sql.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.7.3'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end

#
class SqlParser < Racc::Parser

module_eval(<<'...end sql.y/module_eval...', 'sql.y', 59)

# load 'tokenizer.rb'
def parse(str)
  tokenizer = ::Kaigyo::Tokenizer.new(str)
  @q = tokenizer.token_analysis

  pp @q
  
  do_parse
end

def next_token
  @q.shift
end

...end sql.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    14,    50,    51,    27,     4,    24,    14,    25,    26,     5,
    27,    14,    24,    21,    25,    26,    15,    16,    17,    14,
    18,    19,    15,    16,    17,    14,    18,    15,    16,    17,
    28,    18,    19,    14,    27,    15,    16,    17,    27,    18,
    27,    15,    16,    17,    27,    18,    24,    43,    25,    26,
    27,    45,    24,    27,    25,    26,     4,    65,    66,    53,
    54,    55,    56,    57,    47,    48,    58,    59,    61,    62,
    27,    27,    27,    69,    70,    27,    72 ]

racc_action_check = [
     2,    36,    36,     4,     0,     4,     8,     4,     4,     1,
    16,     9,    16,     3,    16,    16,     2,     2,     2,    10,
     2,     2,     8,     8,     8,    11,     8,     9,     9,     9,
     5,     9,     7,    13,    14,    10,    10,    10,    15,    10,
    17,    11,    11,    11,    21,    11,    21,    18,    21,    21,
    45,    23,    45,    52,    45,    45,    24,    52,    52,    37,
    37,    37,    37,    37,    27,    35,    41,    42,    46,    47,
    48,    49,    58,    61,    63,    69,    70 ]

racc_action_pointer = [
     2,     9,    -4,    10,    -4,    30,   nil,     7,     2,     7,
    15,    21,   nil,    29,    27,    31,     3,    33,    36,   nil,
   nil,    37,   nil,    43,    54,   nil,   nil,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    60,   -12,    44,   nil,   nil,
   nil,    58,    44,   nil,   nil,    43,    58,    62,    63,    64,
   nil,   nil,    46,   nil,   nil,   nil,   nil,   nil,    65,   nil,
   nil,    67,   nil,    68,   nil,   nil,   nil,   nil,   nil,    68,
    69,   nil,   nil ]

racc_action_default = [
   -50,   -50,   -48,   -13,   -50,   -50,    -1,   -48,    -3,    -4,
    -5,    -6,   -11,   -16,   -50,   -50,   -50,   -50,   -50,   -49,
   -12,   -50,   -14,   -20,   -50,   -24,   -25,   -26,    73,    -2,
    -7,    -8,    -9,   -10,   -17,   -50,   -28,   -50,   -40,   -41,
   -42,   -43,   -45,   -47,   -15,   -50,   -50,   -50,   -50,   -50,
   -33,   -34,   -50,   -35,   -36,   -37,   -38,   -39,   -50,   -46,
   -21,   -22,   -27,   -18,   -29,   -30,   -31,   -32,   -44,   -50,
   -50,   -23,   -19 ]

racc_goto_table = [
    35,    37,    22,    42,    40,     1,    38,     6,    34,     7,
    20,    49,    29,    52,    39,    30,    31,    32,    33,    44,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    46,
   nil,   nil,   nil,   nil,    37,    37,   nil,   nil,    67,    63,
    64,   nil,   nil,    60,    42,    68,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    71 ]

racc_goto_check = [
    14,    14,    12,    14,    19,     1,    15,     3,     5,     4,
    11,    17,     3,    18,    12,     4,     4,     4,     4,    12,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     1,
   nil,   nil,   nil,   nil,    14,    14,   nil,   nil,    14,    15,
    15,   nil,   nil,    12,    14,    19,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    14 ]

racc_goto_pointer = [
   nil,     5,   nil,     5,     7,    -5,   nil,   nil,   nil,   nil,
   nil,     7,    -2,   nil,   -14,    -9,   nil,   -25,   -24,   -13,
   nil ]

racc_goto_default = [
   nil,   nil,     2,   nil,   nil,     8,     9,    10,    11,    12,
     3,   nil,   nil,    13,    23,   nil,    36,   nil,   nil,   nil,
    41 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 27, :_reduce_1,
  3, 27, :_reduce_2,
  1, 30, :_reduce_3,
  1, 30, :_reduce_4,
  1, 30, :_reduce_5,
  1, 30, :_reduce_6,
  2, 30, :_reduce_7,
  2, 30, :_reduce_8,
  2, 30, :_reduce_9,
  2, 30, :_reduce_10,
  1, 30, :_reduce_11,
  2, 28, :_reduce_12,
  1, 28, :_reduce_13,
  2, 36, :_reduce_14,
  2, 37, :_reduce_15,
  1, 31, :_reduce_16,
  2, 31, :_reduce_17,
  4, 39, :_reduce_18,
  6, 39, :_reduce_19,
  1, 38, :_reduce_none,
  3, 38, :_reduce_21,
  3, 38, :_reduce_22,
  5, 38, :_reduce_23,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 40, :_reduce_none,
  3, 40, :_reduce_27,
  1, 41, :_reduce_none,
  3, 41, :_reduce_29,
  3, 42, :_reduce_30,
  3, 42, :_reduce_31,
  3, 42, :_reduce_32,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  2, 32, :_reduce_40,
  2, 33, :_reduce_41,
  2, 34, :_reduce_42,
  1, 45, :_reduce_43,
  3, 45, :_reduce_44,
  1, 46, :_reduce_45,
  2, 46, :_reduce_46,
  2, 35, :_reduce_47,
  0, 29, :_reduce_none,
  1, 29, :_reduce_49 ]

racc_reduce_n = 50

racc_shift_n = 73

racc_token_table = {
  false => 0,
  :error => 1,
  :select => 2,
  :from => 3,
  :join => 4,
  :on => 5,
  :as => 6,
  :identifier => 7,
  :punctuation => 8,
  :left_paren => 9,
  :right_paren => 10,
  :number => 11,
  :literal => 12,
  :and => 13,
  :or => 14,
  :equal => 15,
  :less_than => 16,
  :less_than_equal => 17,
  :greater_than => 18,
  :greater_than_equal => 19,
  :where => 20,
  :group_by => 21,
  :order_by => 22,
  :order_option => 23,
  :limit => 24,
  :semi_colon => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "select",
  "from",
  "join",
  "on",
  "as",
  "identifier",
  "punctuation",
  "left_paren",
  "right_paren",
  "number",
  "literal",
  "and",
  "or",
  "equal",
  "less_than",
  "less_than_equal",
  "greater_than",
  "greater_than_equal",
  "where",
  "group_by",
  "order_by",
  "order_option",
  "limit",
  "semi_colon",
  "$start",
  "sql",
  "select_and_from",
  "semi_colon_char",
  "optional_clauses",
  "join_clauses",
  "where_clause",
  "group_by_clause",
  "order_by_clause",
  "limit_clause",
  "select_clause",
  "from_clause",
  "idents",
  "join_clause",
  "ident",
  "conditions",
  "condition",
  "and_or",
  "operator",
  "order_by_idents",
  "order_by_ident" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'sql.y', 2)
  def _reduce_1(val, _values, result)
     result = val.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 3)
  def _reduce_2(val, _values, result)
     result = val.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 6)
  def _reduce_3(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 7)
  def _reduce_4(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 8)
  def _reduce_5(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 9)
  def _reduce_6(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 10)
  def _reduce_7(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 11)
  def _reduce_8(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 12)
  def _reduce_9(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 13)
  def _reduce_10(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 14)
  def _reduce_11(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 17)
  def _reduce_12(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 18)
  def _reduce_13(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 19)
  def _reduce_14(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 21)
  def _reduce_15(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 23)
  def _reduce_16(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 24)
  def _reduce_17(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 25)
  def _reduce_18(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 26)
  def _reduce_19(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'sql.y', 28)
  def _reduce_21(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 29)
  def _reduce_22(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 30)
  def _reduce_23(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'sql.y', 34)
  def _reduce_27(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'sql.y', 37)
  def _reduce_29(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 38)
  def _reduce_30(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 39)
  def _reduce_31(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 40)
  def _reduce_32(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'sql.y', 43)
  def _reduce_40(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 44)
  def _reduce_41(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 45)
  def _reduce_42(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 46)
  def _reduce_43(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 47)
  def _reduce_44(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 48)
  def _reduce_45(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 49)
  def _reduce_46(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'sql.y', 50)
  def _reduce_47(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 48 omitted

module_eval(<<'.,.,', 'sql.y', 52)
  def _reduce_49(val, _values, result)
     result = val
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class SqlParser


# if __FILE__ == $0
# TEST_SQL =<<-SQL
#   select a as aa , b as bb, (select c from hoge where c.id = 1 or hoge.id = 1) as cc inner join piyo as p on p.id = a.id left outer join aaaaa as aaa on aaa.id = a.id where aaa.gid > 1 or aaa.id > 0;
# SQL
#   begin
#     puts '> Please input SQL'
#     sql = gets.chomp
#     # ast = SqlParser.new.parse(TEST_SQL)
#     parsed = SqlParser.new.parse(sql)
#     puts "AST:"
#     pp parsed
#   rescue Racc::ParseError => e
#     $stderr.puts e
#     $stderr.puts e.backtrace
#   end
# end
